name: pull draft from hatenablog

on:
  workflow_dispatch:
    inputs:
      title:
        description: "Draft Entry Title"
        required: true

jobs:
  pull-draft:
    uses: hatena/hatenablog-workflows/.github/workflows/pull-draft.yaml@v1
    with:
      title: ${{ github.event.inputs.title }}
      BLOG_DOMAIN: ${{ vars.BLOG_DOMAIN }}
    secrets:
      OWNER_API_KEY: ${{ secrets.OWNER_API_KEY }}
