name: push draft to hatena blog

on:
  pull_request:
    paths:
      - "draft_entries/**"

jobs:
  pull-draft:
    uses: hatena/hatenablog-workflows/.github/workflows/push-draft.yaml@v1
    secrets:
      OWNER_API_KEY: ${{ secrets.OWNER_API_KEY }}
